FROM node:iron-slim

WORKDIR /app

# copy default uploads
#COPY /api/ /app/api
COPY /src/ /app/src
COPY /package.json /app/
COPY /package-lock.json /app/
COPY /integrations.json /app/

RUN npm ci --omit=dev

CMD ["node", "src/index.js"]
