FROM node:iron-slim

WORKDIR /user/app

# copy default uploads
#COPY /api/ /user/app/api
COPY /src/ /user/app/src
COPY /package.json /user/app/
COPY /package-lock.json /user/app/

RUN npm ci --omit=dev

CMD ["node", "src/index.js"]
