name: deploy

on:
    # manually only
    workflow_dispatch:

# allow only one concurrent run
concurrency: "deploy"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v5

          - name: Build image
            run: cd docker && make build

          - name: Create version from current date and time
            id: get_version
            run: echo "version=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

          - run: docker tag joobydev/jooby-rest-server:latest joobydev/jooby-rest-server:${{ env.version }}

          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Push images
            run: docker image push --all-tags joobydev/jooby-rest-server
