name: test

on:
    # any branch
    push:
        branches:
          - '**'
        # don't run on release tag creation
        tags-ignore:
          - '**'
    pull_request:
    # manually
    workflow_dispatch:

permissions:
    contents: read

# allow only one concurrent run
concurrency: "test"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: checkout
            uses: actions/checkout@v5

          - uses: actions/setup-node@v6
            with:
                node-version: '22.4.x'
                cache: npm

          - run: npm ci
          - run: npm test
